#!/bin/sh


policy='[Policy] Never force push  the branch! (Prevented with pre-push hook.)'

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

push_command=$(ps -ocommand= -p $PPID)

echo $push_command 

is_destructive='force\-f'

will_remove_protected_branch=':'$protected_branch

do_exit(){
  echo $policy
  exit 1
}

if [[ $push_command =~ $is_destructive ]] ; then
  echo " regra de hook"
  do_exit
fi


unset do_exit

exit 0
