#!/bin/bash 

policy='[Policy] Never force push  the branch! (Prevented with pre-push hook.)'


# Test SO Linux or Windows
if [ -f /etc/passwd ]; then

  push_command=$(ps -ocommand= -p $PPID)

else

  push_command=$(WMIC /OUTPUT:STDOUT PROCESS get Caption, Commandline, Processid | grep "git")

fi

do_exit(){
  echo $policy
  exit 1
}

do_success(){
  echo "Pass on pre-push on git Hook."
  exit 0
}

block_force=".*git.*push.*\-\-force"
block_f=".*git.*push.*\-f"

if [[ "$push_command" =~ $block_force || "$push_command" =~ $block_f ]]; then
  do_exit
else
  do_success
fi

unset do_exit

exit 0
