#!/bin/sh


policy='[Policy] Never force push  the branch! (Prevented with pre-push hook.)'

push_command=$(ps -ocommand= -p $PPID)

echo $push_command 
echo "LEO LEO"

is_destructive='force\-f'

will_remove_protected_branch=':'$protected_branch

do_exit(){
  echo $policy
  exit 1
}

do_success(){
  echo "Pass on pre-commit on git Hook."
  exit 0
}

#var1="git push --force origin"
block_force="force"
block_f="\-f"

if [[ "$push_command" =~ $block_force ]]; then
  do_exit
else
  do_success
fi

unset do_exit

exit 0
